name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Change pour 'master' si ta branche principale s'appelle master

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration de Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Installation des dépendances (Contournement conflit TypeScript)
        run: npm install --legacy-peer-deps

      - name: Build de l'application Angular
        # REMPLACE "simontheriault8-cyber" par ton nom de dépôt (repository) si nécessaire
        run: npx ng build --configuration production --base-href /simontheriault8-cyber/

      - name: Déploiement sur GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist/simontheriault8-cyber/browser # Vérifie si ton projet compile bien dans ce sous-dossier browser
          branch: gh-pages
